# Generated by Django 3.2.23 on 2023-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('catagory', models.CharField(choices=[('textbook', 'Textbooks'), ('reference_materials', 'Reference Materials'), ('reserve_collection', 'Reserve Collection'), ('periodicals_journals', 'Periodicals and Journals'), ('fiction_literature', 'Fiction and Literature'), ('science_technology', 'Science and Technology'), ('mathematics', 'Mathematics'), ('social_sciences', 'Social Sciences'), ('humanities', 'Humanities'), ('business_economics', 'Business and Economics'), ('health_sciences', 'Health Sciences'), ('computer_science_it', 'Computer Science and Information Technology'), ('education', 'Education'), ('languages', 'Languages'), ('fine_arts', 'Fine Arts'), ('law_political_science', 'Law and Political Science'), ('environmental_sciences', 'Environmental Sciences'), ('architecture_design', 'Architecture and Design'), ('multidisciplinary_studies', 'Multidisciplinary Studies'), ('career_development_self_help', 'Career Development and Self-Help'), ('new_acquisitions_bestsellers', 'New Acquisitions and Bestsellers'), ('government_publications', 'Government Publications'), ('thesis_dissertations', 'Thesis and Dissertations')], max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
    ]
