# Generated by Django 3.2.23 on 2023-12-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookInfo',
        ),
    ]
