# Generated by Django 3.2.23 on 2023-12-22 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_rename_book_bookinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinfo',
            name='category',
        ),
    ]
