# Generated by Django 3.2.23 on 2023-12-22 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_remove_bookinfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=15),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('borrow', 'Borrow'), ('return', 'Return')], max_length=10)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnedBookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returner_name', models.CharField(max_length=255)),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('due_status', models.TextField(default=None, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookinfo')),
            ],
        ),
    ]
