# Generated by Django 3.2.23 on 2023-12-22 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_alter_transaction_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbookinfo',
            name='returned_date',
        ),
    ]
