# Generated by Django 3.2.23 on 2023-12-22 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_auto_20231223_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookhis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returner_name', models.CharField(max_length=255)),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.bookinfo')),
            ],
        ),
    ]
