# Generated by Django 3.2.23 on 2023-12-22 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0010_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookhis',
            old_name='returner_name',
            new_name='borrower_name',
        ),
        migrations.RemoveField(
            model_name='bookhis',
            name='returned_date',
        ),
    ]
