# Generated by Django 3.2.23 on 2023-12-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0011_auto_20231223_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhis',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
