# Generated by Django 3.2.23 on 2023-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0012_bookhis_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhis',
            name='due_status',
            field=models.TextField(default=None, null=True),
        ),
    ]
