# Generated by Django 3.2.23 on 2023-12-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0013_bookhis_due_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
