# Generated by Django 3.2.23 on 2023-12-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0014_transaction_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='remarks',
        ),
        migrations.AddField(
            model_name='borrowedbookinfo',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbookinfo',
            name='due_status',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='returnedbookinfo',
            name='due_status',
            field=models.TextField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='bookhis',
        ),
    ]
