# Generated by Django 3.2.23 on 2023-12-26 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0015_auto_20231227_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbookinfo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnedbookinfo',
            name='borrowed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returnedbookinfo',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
