# Generated by Django 3.2.23 on 2023-12-26 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0016_auto_20231227_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbookinfo',
            name='due_status',
        ),
    ]
