# Generated by Django 3.2.23 on 2023-12-27 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0017_remove_borrowedbookinfo_due_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
