# Generated by Django 3.2.23 on 2023-12-27 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0019_transactionforuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedbookinfo',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnedbookinfo',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returnedbookinfo',
            name='returned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='TransactionForUser',
        ),
    ]
